services:
  freqtrade:
    build: .
    container_name: freqtrade
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "127.0.0.1:3333:3333"
    volumes:
      - ./freqtrade_data:/freqtrade/user_data
    environment:
      - TZ=Europe/Berlin
    command: trade --config /freqtrade/user_data/config.json